# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eValidationApp', '0002_auto_20170220_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
